Flipped left and right sides and reversed direction
umrover/mrover-workspace pull request #1000
Opened 2022-04-02 19:29 UTC by Polishdudealan

2022-04-03 01:03 UTC, cgiger00 requested changes

2022-04-03 01:03 UTC, cgiger00 commented on jetson/odrive_bridge/src/__main__.py
> +            left_speed, right_speed = -cmd.left, -cmd.right,
can you leave this as cmd.left and cmd.right and just flip the negative sign in modrive.set_vel?

2022-04-03 16:48 UTC, CameronTressler commented
I think I'm missing something, why are we PR-ing this into auton-integration and not auton-drive-change?

2022-04-03 17:27 UTC, cgiger00 commented
they're both being PRed into auton-integration, doesn't rly matter either way imo

2022-04-03 17:46 UTC, tabiosg approved these changes

2022-04-03 18:34 UTC, ankithu approved these changes

2022-04-05 02:02 UTC, CameronTressler approved these changes

2022-04-05 05:49 UTC, cgiger00 approved these changes

2022-04-05 05:49 UTC, merged