[admin] clean up of the pi camera stuff
umrover/mrover-workspace pull request #1006
Opened 2022-04-03 17:51 UTC by cgiger00

PRing it into ISH integration because the rest of the camera code is being merged in w this integration branch anyways

2022-04-03 23:07 UTC, tabiosg requested changes
I was actually planning on keeping the base station gstreamer stuff, it would probably be nice if we didn't remove it?

2022-04-05 07:03 UTC, cgiger00 commented
sg will add back

2022-04-05 16:39 UTC, tabiosg approved these changes

2022-04-05 21:49 UTC, CameronTressler approved these changes

2022-04-05 22:10 UTC, merged