Made requested changes
umrover/mrover-workspace pull request #1010
Opened 2022-04-03 19:39 UTC by mmartin4972

* Specify the -r flag to run only and not build
* Added the export LCM command, which will be executed anytime launch is called
* Added commands to localization launch

2022-04-05 05:48 UTC, cgiger00 requested changes

2022-04-05 05:48 UTC, cgiger00 commented on jarvis_files/jarvis_cmd/src/jarvis/launch.py
> +            ssh=ssh, ip=AUTON_IP, close_terminal = True)
can you add this for drive too?

2022-04-09 18:47 UTC, mmartin4972 commented on jarvis_files/jarvis_cmd/src/jarvis/launch.py
> +            ssh=ssh, ip=AUTON_IP, close_terminal = True)
yes

2022-04-09 19:48 UTC, mmartin4972 commented
Tested on rover

2022-04-11 00:49 UTC, cgiger00 approved these changes
lgtm

2022-04-11 00:50 UTC, merged