[sim] Implemented False Positives Display
umrover/mrover-workspace pull request #1055
Opened 2022-04-16 19:50 UTC by michmli

This adds the display of false positives in the rover's fov, but haven't integrated with the target_detector (so rover isn't detecting false positives yet). 
[
<img width="1489" alt="Screen Shot 2022-04-16 at 3 47 16 PM" src="https://user-images.githubusercontent.com/78882459/163689401-9da15de9-d2d1-4499-8c2f-ffe514173aa5.png">
](url)

2022-04-16 23:54 UTC, cgiger00 commented
what do you mean doesn't have the target detector?

2022-04-16 23:56 UTC, cgiger00 requested changes

2022-04-16 23:56 UTC, cgiger00 commented on pip_deps/jetson_requirements.txt
>  numpy==1.16.2
add these dependencies back?

2022-04-17 18:18 UTC, michmli commented
> 
So far, we've only added the functionality of displaying false positives to the sim, but the rover doesn't detect them as false positive tags.

2022-05-05 06:43 UTC, closed without merging