[teleop] Lcm fix
umrover/mrover-workspace pull request #1064
Opened 2022-04-17 00:02 UTC by CameronTressler

2022-04-17 02:13 UTC, cgiger00 approved these changes

2022-04-17 02:14 UTC, cgiger00 requested changes
can you also change rover_common/heartbeater.py to have OnboartHeartBeater to be JetsonHeartBeater

2022-04-17 16:03 UTC, CameronTressler commented
Ah yeah that would make sense

2022-04-18 03:53 UTC, cgiger00 approved these changes
thx

2022-04-18 03:53 UTC, merged