[teleop] Joint b calibration
umrover/mrover-workspace pull request #1077
Opened 2022-04-26 02:29 UTC by CameronTressler

2022-04-26 02:34 UTC, tabiosg requested changes
Merge conflicts

2022-04-27 03:25 UTC, CameronTressler commented
Oh thanks for fixing conflicts Bryan. Sorry for all the switching around with branches. Should be good now @tabiosg @cgiger00

2022-04-27 04:53 UTC, tabiosg approved these changes

2022-04-27 04:58 UTC, bli76 approved these changes

2022-04-27 14:43 UTC, CameronTressler commented
Merge conflicts was just removing unnecessary toggle button styling

2022-04-27 15:03 UTC, tabiosg approved these changes

2022-04-28 20:01 UTC, cgiger00 requested changes

2022-04-28 20:01 UTC, cgiger00 commented on base_station/gui/src/components/LCMEcho.vue
> +          {'topic': '/joint_b_calibration_data', 'type': 'JointBCalibration'},
same comment as above

2022-04-28 20:01 UTC, cgiger00 commented on base_station/gui/src/components/SATask.vue
> +        {'topic': '/joint_b_calibration_data', 'type': 'JointBCalibration'}
same as above

2022-04-28 20:01 UTC, cgiger00 commented on base_station/gui/src/static/rover_msgs.json
> +    "JointBCalibration": [
same as above

2022-04-28 20:01 UTC, cgiger00 commented on jetson/nucleo_bridge/README.md
>  Message: [JointBCalibration.lcm](https://github.com/umrover/mrover-workspace/blob/master/rover_msgs/JointBCalibration.lcm) \
same as above

2022-05-04 20:07 UTC, cgiger00 reviewed
has this ever been tested with joint B?

2022-05-04 20:08 UTC, cgiger00 approved these changes
^see above comment

2022-05-04 23:22 UTC, tabiosg commented
No this hasn't been tested with joint-b

2022-05-05 22:24 UTC, tabiosg commented
Ok it has been tested with joint-b now

2022-05-06 03:02 UTC, bli76 approved these changes

2022-05-09 14:47 UTC, merged