[admin] travis-free merge post auton-integration
umrover/mrover-workspace pull request #1093
Opened 2022-05-16 18:36 UTC by cgiger00

2022-05-16 21:33 UTC, tabiosg approved these changes
if odrive stuff works then it should be good esw's end

2022-05-16 23:39 UTC, tabiosg requested changes

2022-05-16 23:39 UTC, tabiosg commented on base_station/gui/src/components/DriveVelDataH.vue
> +      <td class = "tableElement">{{drive_vel_data.middleLeft.velocity}} counts/sec</td>
change to m/sec

2022-05-16 23:41 UTC, tabiosg approved these changes

2022-05-17 05:22 UTC, niwhsa9 approved these changes

2022-05-17 19:28 UTC, merged