[percep] AR tag streaming
umrover/mrover-workspace pull request #1122
Opened 2022-05-27 19:09 UTC by qhdwight

I would be extremely cautious about merging this before being thoroughly tested.

2022-05-28 01:17 UTC, niwhsa9 approved these changes
LGTM. 

really stupid nit which you should ignore: u can save a cvtcolor operation by swapping channels on the reciever end of the gstreamer pipe which frees up some time on the jetson, but its negligible anyway.

2022-05-28 02:26 UTC, cgiger00 commented
yes agreed, will test ASAP

2022-05-28 02:27 UTC, cgiger00 requested changes

2022-05-28 02:27 UTC, cgiger00 commented on jetson/percep/main.cpp
> +                                    "rtph264pay ! udpsink host=127.0.0.1 port=5000";
can you change it to port 5002 or something? in auton 5000 and 5001 are being used by the regular usb cameras

2022-05-28 19:26 UTC, cgiger00 approved these changes
testing has been good w this

2022-05-29 02:48 UTC, ankithu approved these changes

2022-05-29 02:49 UTC, tabiosg approved these changes
crazy!!!

2022-06-01 01:27 UTC, cgiger00 commented
fixed with https://github.com/umrover/mrover-workspace/pull/1132

2022-06-01 01:27 UTC, closed without merging