[esw, teleop] operator integration
umrover/mrover-workspace pull request #1124
Opened 2022-05-27 20:18 UTC by cgiger00

2022-05-27 21:42 UTC, cgiger00 commented on base_station/gui/src/components/ERDRoverMap.vue
> +        <div v-if="index===highlightedWaypoint">
@jnnanni is this now missing from the AutonRoverMap.vue file?

2022-05-27 21:43 UTC, tabiosg commented on ansible/roles/base_station_services/files/rover-base_station_gstreamer_3.service
> +[Unit]
ill delete the extra gstreamer services

2022-05-27 22:30 UTC, tabiosg approved these changes

2022-05-28 00:06 UTC, cgiger00 commented on ansible/roles/base_station_services/files/rover-base_station_gstreamer_3.service
> +[Unit]
right forgot about that

2022-05-28 01:22 UTC, tabiosg requested changes
Jetson cameras doesn't pass linter... I thought I tested this :(( I'll make a pr tomorrow morning (?)

2022-05-28 02:22 UTC, cgiger00 commented
sad

2022-05-28 16:57 UTC, tabiosg approved these changes

2022-05-28 19:15 UTC, sashreek1 approved these changes

2022-05-28 19:29 UTC, merged