[teleop] Add conversions for chlorophyll spectral
umrover/mrover-workspace pull request #1131
Opened 2022-05-29 06:19 UTC by CameronTressler

2022-05-29 06:20 UTC, CameronTressler commented
Message from Gabe:

Here are the numbers for the conversion from spectral 2 and spectral 1 to spectral 0. It's kind of hard to label these clearly but "x1" and "x2" are the measured values currently being printed out for spectral sensors 1 and 2, and "y" is the converted value for each.

Spectral 1: y1 = (1 / 0.94) * (x1 - 23.28)
Spectral 2: y2 = (1 / 0.9969) * (x2 + 32.8575)

2022-05-29 12:40 UTC, tabiosg reviewed
I'll test this later and then I'll approve if it works

2022-05-29 12:40 UTC, tabiosg commented on base_station/gui/src/components/Chlorophyll.vue
> +      return (1 / 0.94) / (sensor_reading - 23.28)
Will the gui break if we get a divide by 0 problem

2022-05-29 12:41 UTC, tabiosg commented on base_station/gui/src/components/Chlorophyll.vue
> +      return (1 / 0.94) / (sensor_reading - 23.28)
Actually, Gabe said it was multiply, not divide

2022-05-29 12:42 UTC, tabiosg requested changes
Change to multiply not divide in equation i think

2022-05-30 01:52 UTC, cgiger00 approved these changes

2022-05-30 02:07 UTC, tabiosg approved these changes

2022-05-30 02:36 UTC, merged

2022-05-30 02:36 UTC, cgiger00 commented
NOTE: ***AFTER THE CODE FREEZE*** needed addition for science that we had missed