[Nav] Zed gimbal addition
umrover/mrover-workspace pull request #587
Opened 2021-02-06 18:16 UTC by ankithu

#388 , #389

This commit adds a Gimbal class to allow control of the Zed Gimbal for improved search efficiency. It also adds the use of that gimbal class through added states to both the Gate Traversal and Search state machines. The basic functionality is that instead of turning 360 degrees when we get to a point we want to search. We turn the gimbal to positive 150 degrees then to -150 degrees then back to 0. This number is editable through the config. Additionally, code was added to receive and send gimbal LCM messages. Additionally, as this is a new feature, a boolean was added to the config that can be turned on or off to enable or disable Zed Gimbal functionality.

Changes were tested in the simulator. The search state machine changes were tested with various locations of waypoints and AR tags, in all instances that I tested, the rover was able to successfully find the AR tags. The gate traversal algorithm also worked with various orientations of the gates and distances from the point (enough to enter the diamond search pattern) and the rover made it through even with the gate pointing in a direction that would be opposite from ideal. Additionally, the enable and disable gimbal switch was tested and works in the sim.

2021-02-06 18:20 UTC, ankithu commented
Hi, just a quick question, what would be the best way to resolve the merge conflicts? Manually or should I merge in the auton integration branch with this branch or maybe rebase zed_gimbal_addition on top of the auton_integration branch?

2021-02-06 18:30 UTC, aswarner commented
I think you should rebase auton_integration under your changes, then you will probably need to manually resolve remaining conflicts in your editor. I am surprised there were issues since you pulled from auton_integration to start working with Zack's code. But that's okay. update your PR after fixing your conflicts

2021-02-06 18:32 UTC, aswarner commented
also, remove amverni from the review since he is retired. and you can keep James on, but since he worked with you he shouldn't be a primary reviewer. you should have 
1. a member familiar with the specific code in question (since this is nav code, you should add me for this)
2. a member familiar with MRover coding standards and review process (david smith @DavidSmith166 or raytitan) 
3. a new member (I think we suggested Rajin, but it can be anyone who will be responsive)

2021-02-06 20:46 UTC, ankithu commented
Ok merge conflicts are fixed and I adjusted the reviewers (minus Rajin, waiting on a username)

2021-02-06 20:48 UTC, aswarner commented
@ankithu  nice job fixing the merge conflicts! did you test after making the changes?

2021-02-06 21:00 UTC, ankithu commented
Ok just tested and everything seems to work after a silly mistake was fixed

2021-02-07 18:00 UTC, aswarner requested changes
We need to make two major changes: avoiding using "target yaw/angle" in gimbal functions and variables, and refactoring gateSpinWait functions and searchSpinWait/searchGimbalWait into just gateWait and searchWait.

Buggy simulator code is still in autonomous integration branch - I will revert, then we need to pull the modified files from this PR

2021-02-07 19:18 UTC, aswarner commented on jetson/nav/gate_search/gateStateMachine.cpp
> +    //set the target yaw to wherever the next stop on the gimbals path is
change comments in this function to say desired/phase etc, not target

2021-02-07 19:36 UTC, aswarner requested changes

2021-02-07 19:36 UTC, aswarner commented on jetson/nav/gimbal.hpp
> +        //sets the target yaw of the gimbal
remove "target"

2021-02-07 19:36 UTC, aswarner commented on jetson/nav/gimbal.hpp
> +        bool setDesiredGimbalYaw( double target );
takes input "target"  - remove

2021-02-07 19:40 UTC, John-Trager commented on simulators/nav/src/store/modules/simulatorState.ts
> +// const MAX_RECENT_PATH_LEN = 100;
does this need to stay in?

2021-02-07 19:43 UTC, ankithu commented on simulators/nav/src/store/modules/simulatorState.ts
> +// const MAX_RECENT_PATH_LEN = 100;
discussed offline

2021-02-07 20:07 UTC, aswarner commented
can you remove the extra waits in between reaching the first 150 degrees and after reaching the -150? e.g. remove redundant waits at the same angle

2021-02-08 16:55 UTC, aswarner approved these changes
looks ready to me! I made two small changes. other reviewers, you will need to modify the json file to make useGimbal true before testing. I made the default false (use spin for search).

2021-02-08 23:26 UTC, John-Trager approved these changes
Reviewed code and ran in sim. No problems were found looks good.

2021-02-09 01:35 UTC, raytitan approved these changes
Let's get this tested!

2021-02-09 01:36 UTC, merged