[nav] Standardize mPhoebe as a member variable in child state machine classes
umrover/mrover-workspace pull request #596
Opened 2021-02-14 19:04 UTC by radraju

Resolves #427

Standardized mPhoebe and mRoverConfig as member variables in searchStateMachine and obstacleAvoidanceStateMachine instead of passing a rover variable into functions and child class objects.

This change was tested in the navigation simulator to verify that search and obstacle avoidance worked as usual.

2021-02-14 20:06 UTC, ankithu requested changes
See comments, other than those two minor things it seems to work well

2021-02-14 20:06 UTC, ankithu commented on jetson/nav/search/searchStateMachine.cpp
> +
When I compile I get a warning here. Switching the order of the initializer list so it matches the order of initialization in the hpp file (switch mPhoebe and mRoverConfig) should make the warning go away. I know it doesn't make a difference but its probably just a best practice to not have warnings

2021-02-14 20:06 UTC, ankithu commented on jetson/nav/obstacle_avoidance/obstacleAvoidanceStateMachine.cpp
> +    ,  mJustDetectedObstacle( false ) {}
When I compile I get a warning here. Switching the order of the initializer list so it matches the order of initialization in the hpp file (switch mPhoebe and mRoverConfig) should make the warning go away. I know it doesn't make a difference but its probably just a best practice to not have warnings

2021-02-18 00:24 UTC, aswarner commented on jetson/nav/obstacle_avoidance/obstacleAvoidanceStateMachine.cpp
> +ObstacleAvoidanceStateMachine::ObstacleAvoidanceStateMachine( StateMachine* stateMachine_, Rover* rover, const rapidjson::Document& roverConfig)
add space between parameters and )

2021-02-18 00:26 UTC, aswarner commented on jetson/nav/obstacle_avoidance/obstacleAvoidanceStateMachine.hpp
> +    ObstacleAvoidanceStateMachine( StateMachine* stateMachine_, Rover* rover, const rapidjson::Document& roverConfig);
add space between parameters and )

2021-02-18 00:51 UTC, aswarner commented on jetson/nav/search/spiralInSearch.hpp
> +    : SearchStateMachine( stateMachine_, rover, roverConfig) {}
space after roverConfig

2021-02-18 01:46 UTC, ankithu approved these changes

2021-02-18 01:47 UTC, ankithu commented
compiles without warning and tested in sim

2021-02-18 15:41 UTC, aswarner submitted a review, later dismissed

2021-02-19 05:27 UTC, DavidSmith166 submitted a review, later dismissed
this is a good start, now you can work on changing the name from phoebe to rover

2021-03-07 19:36 UTC, ankithu approved these changes
Looked over the code, ran it on the sim, looks good to me.

2021-03-08 17:51 UTC, DavidSmith166 approved these changes

2021-03-18 00:48 UTC, aswarner approved these changes

2021-03-18 01:19 UTC, merged