Complete Redesign of Science GUI
umrover/mrover-workspace pull request #751
Opened 2021-10-03 19:26 UTC by jnnanni

All of the changes to the Science GUI made during the last school year. Changes are teleop-science-gui-improvments project. The changes in this PR are in the in progress column.

2021-10-03 22:17 UTC, CameronTressler commented
Instead of creating a Google Doc with screenshots of LCMs, can you add a README.md file to base_station/gui/ and enumerate which LCM messages/channels are supposed to be sent and received (and say for each that you tested it). For now it can be specific to the Science GUI even though it's in the gui/ directory

2021-10-07 02:26 UTC, CameronTressler approved these changes
Readme will need to be updated with more detail in the future, but I think this should be sufficient for now

2021-11-12 06:39 UTC, cgiger00 requested changes

2021-11-12 06:39 UTC, cgiger00 commented on base_station/gui/src/components/SATask.vue
> +import OdometryReading from './OdometryReadingSA.vue'
do we need odom data in science?

2021-11-12 06:39 UTC, cgiger00 commented on base_station/gui/src/components/SATask.vue
> +import OdometryReading from './OdometryReadingSA.vue'
we aren't planning for the gps to be plugged in at least during this

2021-11-12 06:39 UTC, cgiger00 commented on base_station/gui/src/static/rover_msgs.json
>          "Mosfet",
can you get rid of this

2022-02-10 00:23 UTC, closed without merging