Updating main with UM7 Code
umrover/mrover-workspace pull request #813
Opened 2021-12-01 08:35 UTC by rushiltalla

2021-12-05 17:40 UTC, cgiger00 commented on beaglebone/imu/README.md
> +
i guess this is fine for now i'd link the calibration guide you sent in #auton-integration here too

2021-12-05 17:41 UTC, cgiger00 approved these changes

2021-12-05 18:09 UTC, nkr101 approved these changes

2021-12-05 18:21 UTC, zwgold approved these changes

2021-12-09 12:53 UTC, mmartin4972 requested changes
What kind of testing has been performed on this code? Before we merge it in, we need to make sure the code has been integration tested. Could you provide a paragrap about when this code was integration tested?

2022-01-24 23:58 UTC, closed without merging