Added Nav State Color changing box and made space to add Zed Camera Feed under waypoint Editor
umrover/mrover-workspace pull request #875
Opened 2022-01-27 01:03 UTC by jnnanni

2022-01-30 17:26 UTC, CameronTressler approved these changes

2022-01-31 23:42 UTC, cgiger00 requested changes

2022-01-31 23:42 UTC, cgiger00 commented on base_station/gui/src/components/AutonTask.vue
> +        this.nav_state_color = "#4695FF"
can this number #4695FF be changed to be a variable name for readability? is this supposed to be blue?

2022-01-31 23:51 UTC, zwgold approved these changes

2022-02-07 00:05 UTC, cgiger00 approved these changes

2022-02-07 00:05 UTC, merged