Add ESW science bridge code for mosfets, servos, and spectrals
umrover/mrover-workspace pull request #893
Opened 2022-02-03 03:56 UTC by tabiosg

2022-02-05 09:33 UTC, cgiger00 commented on jetson/science_bridge/README.md
> +`$TRIAD, d0_msb_ch0, d0_lsb_ch0, d0_msb_ch1, d0_lsb_ch1, d0_msb_ch2, d0_lsb_ch2, d0_msb_ch3, d0_lsb_ch3, d0_msb_ch4, d0_lsb_ch4, d0_msb_ch5, d0_lsb_ch5, d1_msb_ch0, d1_lsb_ch0, d1_msb_ch1, d1_lsb_ch1
its really 1 device 18 channels but 3 chips...i guess make sure the device order matches the channels (1-18/the letters they map to) you publish to

2022-02-05 09:33 UTC, cgiger00 commented on jetson/science_bridge/README.md
> +- `$THERMISTOR,<temp0>,<temp1>,<temp2>`
comma not at the end?

2022-02-13 00:43 UTC, CameronTressler requested changes

2022-02-13 00:43 UTC, CameronTressler commented on rover_msgs/CarouselData.lcm
> +	// 0 is B, 1 is A, 2 is C
2 is A, 1 is B, 0 is C

2022-02-13 00:55 UTC, CameronTressler approved these changes

2022-02-13 01:01 UTC, merged