Integration update
umrover/mrover-workspace pull request #944
Opened 2022-03-11 03:59 UTC by mmartin4972

2022-03-12 00:02 UTC, cgiger00 requested changes

2022-03-12 04:38 UTC, CameronTressler commented on base_station/gui/src/components/RATask.vue
> +<<<<<<< HEAD
Uh whoops, there goes my faith in vscode. Sorry about this

2022-03-12 04:40 UTC, CameronTressler commented on base_station/gui/src/components/RATask.vue
> +<<<<<<< HEAD
wait these aren't in the code I pushed, they're all outdated. Maybe Github didn't update and you made these comments right after I pushed or something?... Idk but these should be fixed

2022-03-12 19:34 UTC, CameronTressler approved these changes

2022-03-12 19:58 UTC, zwgold commented
Looks fine to me. There are 2 recent commits to main that are not merged in, do we want to include those as well with this PR?

2022-03-12 19:58 UTC, zwgold approved these changes

2022-03-13 20:07 UTC, cgiger00 commented on base_station/gui/src/components/RATask.vue
> +<<<<<<< HEAD
no i think these are from the merge/rebase matt is doing

2022-03-15 04:28 UTC, cgiger00 reviewed
can this be rebased again? main has been updated w some more significant changes (like the drive and sim stuff) recently

2022-03-17 00:31 UTC, cgiger00 approved these changes
lgtm

2022-03-17 00:32 UTC, merged