[teleop] Added an auto shutdown timer for UV bulb
umrover/mrover-workspace pull request #997
Opened 2022-03-31 00:50 UTC by catkims

<img width="336" alt="image" src="https://user-images.githubusercontent.com/79539806/160954294-311e2d57-6f7a-41dc-8327-f7c6a70b167f.png">

2022-03-31 01:55 UTC, CameronTressler commented on base_station/gui/src/components/Chlorophyll.vue
> +      <span class="toggle__switch" v-if="UVLED == 1" v-on:click="UVLED=0, UVshutdown(false)"></span>
The above two lines could be condensed to one line if we use the value of UVLED in the on:click= part

2022-03-31 01:56 UTC, CameronTressler requested changes

2022-03-31 01:56 UTC, CameronTressler commented on base_station/gui/src/components/Chlorophyll.vue
> +      <span class="toggle__switch" v-if="shutdown == 1" v-on:click="shutdown=0"></span>
Similarly this code could be condensed

2022-03-31 01:58 UTC, CameronTressler commented
My understanding was that the Scoop UV bulb should be set on a timer. Not the Chlorophyll UV. You should check with Gabe which he wants.

Sorry I didn't realize this confusion earlier when we were looking at this together

2022-03-31 20:56 UTC, cgiger00 commented
im under that impression too --it's the scoop UV, can this PR be turned into a draft in the meantime while that's being looked into?

2022-04-03 17:00 UTC, jnnanni approved these changes
Lg2m

2022-04-05 01:08 UTC, CameronTressler requested changes

2022-04-05 01:08 UTC, CameronTressler commented on base_station/gui/src/components/ScoopUV.vue
> +      if (this.shutdown === 1) {
So looking at this more, my concern is we could turn it on, turn it off, turn it on, and then the first timeout would turn it off in shorter than 2 minutes. Can you use the cleartimeout function to mitigate this?
https://developer.mozilla.org/en-US/docs/Web/API/clearTimeout

2022-04-10 20:43 UTC, CameronTressler approved these changes
lgtm

2022-04-11 00:47 UTC, cgiger00 approved these changes

2022-04-11 00:47 UTC, merged